# Generated by Django 2.1.7 on 2019-03-22 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190322_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenting_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.Post'),
        ),
    ]
